decision_supi1:
  supi_imsi: "208950000000031"
  pcc_rules: 
    - non-gbr-rule-5qi-9
    - gbr-rule-5qi-1

decision_supi2:
  supi_imsi: "208950000000032"
  pcc_rules:
    - non-gbr-rule-5qi-9
    - gbr-rule-5qi-5

decision_supi3:
  supi_imsi: "208950000000033"
  pcc_rules:
    - gbr-rule-5qi-1

decision_dnn:
  dnn: default
  pcc_rules:
    - non-gbr-rule-5qi-9

decision_default:
  default: true
  pcc_rules:
    - non-gbr-rule-5qi-9

decision_slice:
  slice: 
    sst: 222
    sd: "123"
  pcc_rules:
    - non-gbr-rule-5qi-9