non-gbr-rule-5qi-9:
  flowInfos:
    - flowDescription: permit out ip from any to assigned
      packetFilterUsage: true
  precedence: 10
  refQosData:
    - non-gbr-qos-5qi-9

gbr-rule-5qi-1:
  flowInfos:
    - flowDescription: permit out 6 from 1.2.3.4 80, 8080-9090 to assigned
      packetFilterUsage: true
  precedence: 9
  refQosData:
    - gbr-qos-5qi-1

gbr-rule-5qi-5:
  flowInfos:
    - flowDescription: permit out ip from 1.1.1.2 to assigned
      packetFilterUsage: true
  precedence: 8
  refQosData:
    - gbr-qos-5qi-5
