---
{{- if .Values.multus.n2Interface.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-n2
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": {{- cat .Values.multus.n2Interface.hostInterface | nospace | quote }},
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.n2Interface.ipAdd "/" .Values.multus.n2Interface.netmask | nospace | quote }}
                }
        ]
        {{- if .Values.multus.n2Interface.routes }}
        ,"routes":  {{- .Values.multus.n2Interface.routes | toJson }}
        {{- end }}
      }
    }'
{{- end }}
---
{{- if .Values.multus.n3Interface.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-n3
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": {{- cat .Values.multus.n3Interface.hostInterface | nospace | quote }},
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.n3Interface.ipAdd "/" .Values.multus.n3Interface.netmask | nospace | quote }}
                }
        ]
        {{- if .Values.multus.n3Interface.routes }}
        ,"routes":  {{- .Values.multus.n3Interface.routes | toJson }}
        {{- end }}
      }
    }'
{{- end }}
---
{{- if .Values.multus.ru1Interface.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-ru1
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": {{- cat .Values.multus.ru1Interface.hostInterface | nospace | quote }},
      {{- if .Values.multus.ru1Interface.mtu }}
      "mtu": {{ .Values.multus.ru1Interface.mtu }},
      {{- end }}
      "mode": "bridge",
      "ipam": {
        {{- if eq .Values.multus.ru1Interface.ipAdd "dhcp" }}
        "type": "dhcp"
        {{- else }}
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.ru1Interface.ipAdd "/" .Values.multus.ru1Interface.netmask | nospace | quote }}
                }
        ]
        {{- end }}
      }
    }'
{{- end }}
---
{{- if .Values.multus.ru2Interface.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-ru2
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": {{- cat .Values.multus.ru2Interface.hostInterface | nospace | quote }},
      {{- if .Values.multus.ru2Interface.mtu }}
      "mtu": {{ .Values.multus.ru2Interface.mtu }},
      {{- end }}
      "mode": "bridge",
      "ipam": {
        {{- if eq .Values.multus.ru2Interface.ipAdd "dhcp" }}
        "type": "dhcp"
        {{- else }}
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.ru2Interface.ipAdd "/" .Values.multus.ru2Interface.netmask | nospace | quote }}
                }
        ]
        {{- end }}
      }
    }'
{{- end }}

